### PR TITLE
feature/isEmpty

### PR DESCRIPTION
**Pull request by evanliomain**
feat(isempty): add isEmpty function
An empty value correspond to undefined, null, empty array/string or an object with no property.

### CODE REVIEW

**Comment by gregorybarale** [comment]
Ok for the two functions, but i wonder if there is a better name for _isValid_?

**Comment by evanliomain** [comment]
> Ok for the two functions, but i wonder if there is a better name for _isValid_?

I agree, I don't know if it's the best name. I got inspired from [isValid](https://vega.github.io/vega/docs/expressions/#isValid) vega version.

Do you have any other idea ?

**Comment by evanliomain** [comment]
> > Ok for the two functions, but i wonder if there is a better name for _isValid_?

> Do you have any other idea ?

- _isDefined_

**Comment by evanliomain** [comment]
I create 2 PR to had this 2 functions: isEmpty and isNil.
This PR make too much change.

**Pull request closed without merging**
